#!/usr/bin/env bash
# Write a Bash script that loops from 1 to 10 and: displays bad luck for the 4th loop iteration , displays good luck for the 8th loop iteration , displays Best School for the other iterations.
c=0
t=10
while [ "$c" -lt "$t" ]
do
	if [ "$c" -eq 3 ]
then
		echo "Bad Luck"
	elif [ "$c" -eq 7 ]
then
		echo "Good Luck"
else
		echo "Best School"
fi
	(( c++ ))
done
