#!/usr/bin/env bash
# Write a Bash script that displays the time for 12 hours and 59 minutes: display hours from 0 to 12 ,display minutes from 1 to .
HOUR=0
while [ "$HOUR" -lt 13 ]; do
    echo "Hour: $HOUR"
    MINUTES=1
while [ "$MINUTES" -lt 60 ]; do
    echo "$MINUTES"
 MINUTES='expr MINUTES+1'
done
 HOUR='expr HOUR+1'
done
