#!/usr/bin/env bash
# Write a Bash script that
touch /var/run/myscript.pid
pgrep -f "10-process_and_pid_file" > /var/run/myscript.pid
trap "echo 'I hate the kill command'; rm /var/run/myscript.pid; exit" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "rm -f /var/run/myscript.pid; exit" SIGQUIT
while true
do
echo "To infinity and beyond"
sleep 2
done
