#!/usr/bin/env bash
#rograms that are detached from the terminal and running in the background are called daemons or processes, need to be managed. The general minimum set of instructions is: start, restar
caja=$1
tmpfile="/var/run/my_process.pid"
start_et_createFile()
        {
   	./manage_my_process & 
        sudo touch /var/run/my_process.pid
        echo "$!" > "$tmpfile"       
	}
kill_et_rmFile()
        {
        sudo pkill -f "./manage_my_process"
        sudo rm -f "/var/run/my_process.pid"

        }
stop_rm_start_createFile()
           {
           sudo pkill -f "./manage_my_process"
           sudo rm -f "/var/run/my_process.pid"
           ./manage_my_process &
	   sudo touch /var/run/my_process.pid
	   echo "$!" > "$tmpfile" 
          }


  case "$caja" in
	        
	   start) echo "manage_my_process started"
		   start_et_createFile
		   ;;
	  
	   stop) echo "manage_my_process stopped"
		   kill_et_rmFile
		   ;;
		        
	   restart) echo "manage_my_process restarted"
		   stop_rm_start_createFile
		   ;;
			    
   *) echo "Usage: manage_my_process {start|stop|restart}"
				   	;;
  esac
